<div class="ticket-management" 
    data-currentpage="<?php echo $this->getCurrentPage(); ?>" 
    data-totalpages="<?php echo $this->getTotalPages() ?>" 
    data-baseurl="<?php echo $this->getUrl('*/*/*'); ?>"
    data-filterid="<?php echo $this->getRequest()->getParam('filter_id', ''); ?>">
    <div class="ticket-headings" >
        <h1>Manage Tickets</h1>
        <button class="add-filter-btn">Add Filter</button>
    </div>
    <div class="ticket-filters">
        <h4>Available Filters</h4>
        <?php foreach ($this->getAllFilters() as $filter): ?>
            <a href="<?php echo $this->getUrl('adminhtml/ticket/index').'?filter_id='.$filter->getId(); ?>"><?php echo $filter->getName(); ?></a>
        <?php endforeach; ?>
    </div>
    <?php 
    ?>

    <table class="ticket-grid">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Description</th>
                <th>Priority</th>
                <th>Assigned By</th>
                <th>Assigned To</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->getTicketCollection()->getItems() as $ticket): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($ticket->getId()); ?></td>
                    <td><?php echo $this->escapeHtml($ticket->getTitle()); ?></td>
                    <td><?php echo $this->escapeHtml($ticket->getDescription()); ?></td>
                    <td><?php echo $this->escapeHtml($ticket->getPriority()); ?></td>
                    <td><?php echo $this->getUserName($ticket->getAssignedBy()); ?></td>
                    <td><?php echo $this->getUserName($ticket->getAssignedTo()); ?></td>
                    <td class="status" style="background-color:<?php echo $this->getStatusColorCode($ticket->getStatus()); ?>; color:#fff">
                        <?php echo $this->escapeHtml($this->getLabelOfCode($ticket->getStatus())); ?>
                    </td>
                    <td>
                        <a class="view-button" href="<?php echo $this->getUrl('adminhtml/ticket/view', array('id' => $ticket->getId())); ?>">
                            View
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="custom-pagination">
        <ul class="pagination"></ul>
    </div>
</div>

<div class="filterModal" tabindex="-1" role="dialog">
    <form class="filterForm" method="post" action="<?php echo $this->getUrl('adminhtml/filter/save'); ?>">
    <?php echo $this->getBlockHtml('formkey') ?>
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Add Filter</h2>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <label for="selectStatus">Select Status:</label>
                    <select name="status[]" id="selectStatus" class="form-control" multiple>
                        <?php foreach ($this->getAllStatus() as $status): ?>
                            <option value="<?php echo $status->getCode(); ?>"><?php echo $status->getLabel(); ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="modal-body">
                    <label for="selectAssignedTo">Select Assigned To:</label>
                    <select name="assigned_to[]" id="selectAssignedTo" class="form-control" multiple>
                        <?php foreach ($this->getAdminUsers() as $user): ?>
                            <option value="<?php echo $user->getId(); ?>"><?php echo $user->getUsername(); ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="modal-body">
                    <label for="filterSelect">Select User:</label>
                    <select name="user" id="filterSelect" class="form-control">
                        <?php foreach ($this->getAdminUsers() as $user): ?>
                            <option value="<?php echo $user->getId(); ?>"><?php echo $user->getUsername(); ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="modal-body">
                    <label for="addDays">Add Days:</label>
                    <input type="number" name="days" min="1">
                </div>
                <div class="modal-body">
                    <label for="filterName">Add Filter Name:</label>
                    <input type="text" name="name">
                </div>
                <div class="modal-footer">
                    <button type="submit" class="saveFilterBtn">Save Filter</button>
                </div>
            </div>
        </div>
    </form>
</div>
