<?php $ticket = $this->getTicketDetails(); ?>
<?php $adminUsers = $this->getAdminUsers(); ?>
<?php $allStatus = $this->getAllStatus(); ?>
<?php $comments = $this->commentExist($ticket->getTicketId());?>

<div class="ticket-details">
    <h1><?php echo $this->escapeHtml($this->__('Ticket Details')); ?></h1>
    
    <div class="ticket-item">
        <div class="ticket-label"><?php echo $this->__('Ticket ID'); ?>:</div>
        <div class="ticket-value"><?php echo $this->escapeHtml($ticket->getTicketId()); ?></div>
    </div>

    <div class="ticket-item">
        <div class="ticket-label"><?php echo $this->__('Title'); ?>:</div>
        <div class="ticket-value"><?php echo $this->escapeHtml($ticket->getTitle()); ?></div>
    </div>

    <div class="ticket-item">
        <div class="ticket-label"><?php echo $this->__('Description'); ?>:</div>
        <div class="ticket-value"><?php echo $this->escapeHtml($ticket->getDescription()); ?></div>
    </div>

    <div class="ticket-item">
        <div class="ticket-label"><?php echo $this->__('Assigned By'); ?>:</div>
        <div class="ticket-value">
            <select class="editable" name="assigned_by" data-id="<?php echo $ticket->getTicketId(); ?>" data-url="<?php echo $this->getUpdateUrl() ?>">
                <?php foreach ($adminUsers as $user): ?>
                    <option value="<?php echo $user->getId(); ?>" <?php if ($ticket->getAssignedBy() == $user->getId()) echo 'selected'; ?>>
                        <?php echo $this->escapeHtml($user->getUsername()); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="ticket-item">
        <div class="ticket-label"><?php echo $this->__('Assigned To'); ?>:</div>
        <div class="ticket-value">
            <select class="editable" name="assigned_to" data-id="<?php echo $ticket->getTicketId(); ?>" data-url="<?php echo $this->getUpdateUrl() ?>">
                <?php foreach ($adminUsers as $user): ?>
                    <option value="<?php echo $user->getId(); ?>" <?php if ($ticket->getAssignedTo() == $user->getId()) echo 'selected'; ?>>
                        <?php echo $this->escapeHtml($user->getUsername()); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="ticket-item">
        <div class="ticket-label"><?php echo $this->__('Priority'); ?>:</div>
        <div class="ticket-value"><?php echo $this->escapeHtml($ticket->getPriority()); ?></div>
    </div>

    <div class="ticket-item">
        <div class="ticket-label"><?php echo $this->__('Status'); ?>:</div>
        <div class="ticket-value">
            <select style="background-color:<?php echo $this->getStatusColorCode($ticket->getStatus()); ?>;color:#fff" class="editable status" name="status" data-id="<?php echo $ticket->getTicketId(); ?>" data-url="<?php echo $this->getUpdateUrl() ?>">
                <?php foreach ($allStatus as $status): ?>
                    <option style="background-color:<?php echo $this->getStatusColorCode($status->getCode()); ?>;" class="editable" name="status" data-id="<?php echo $ticket->getTicketId(); ?>"  value="<?php echo $status->getCode(); ?>" <?php if ($ticket->getStatus() == $status->getCode()) echo 'selected'; ?>>
                        <?php echo $this->escapeHtml($status->getLabel()); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</div>

<script src="https://cdn.ckeditor.com/4.17.1/standard/ckeditor.js"></script>
<?php if (!$comments): ?>
<div class="comment-section">
    <h2><?php echo $this->__('Post a Comment'); ?></h2>
    <form id="comment-form" method="post", action="<?php echo $this->getSaveCommentUrl() ?>">
        <?php echo $this->getBlockHtml('formkey') ?>
        <input type="hidden" name="ticket_id" value="<?php echo $ticket->getTicketId() ?>">
        <input type="hidden" name="user_id" value="<?php echo $this->getCurrentUser() ?>">
        <div class="comment-item">
            <textarea name="comment" id="commentBox" placeholder="<?php echo $this->__('Write your comment here...'); ?>"></textarea>
        </div>
        <div class="comment-item">
            <button type="submit"><?php echo $this->__('Submit Comment'); ?></button>
        </div>
    </form>
</div>
<?php endif; ?>

<div class="comment-table">

<?php 
    // echo $this->getChildHtml('ticket.view.comment');
    echo $this->getChildHtml('comment');
?>
</div>